### ISSUE TITLE
[Feature] Translation

### ISSUE THREAD

**Issue by gabsdotco** [biewxw/corona.log#2]
### Description

One of the complaints regarding the project is the lack of translation into other languages.

With that in mind, it would be interesting to add this functionality through [i18n](https://github.com/kazupon/vue-i18n) to Vue.js, thus being able to not only provide the translation of the project but also the contribution with the translation.

### Tasks

- [X] i18n - Implement the plugin
- [X] i18n - Create vars for "english" and "portuguese"
- [X] Moment - Change to the vue plugin
- [ ] Moment - Add the locale change
- [ ] UI - Create the language selector
